config/routes.rb
Rails.application.routes.draw do
  resources :papers
  resources :manuscripts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manuscript.rb
class Manuscript < ActiveRecord::Base
end

app/models/paper.rb
class Paper < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/manuscripts_controller.rb
class ManuscriptsController < ApplicationController
  before_action :set_manuscript, only: [:show, :edit, :update, :destroy]

  # GET /manuscripts
  # GET /manuscripts.json
  def index
    @manuscripts = Manuscript.all
  end

  # GET /manuscripts/1
  # GET /manuscripts/1.json
  def show
  end

  # GET /manuscripts/new
  def new
    @manuscript = Manuscript.new
  end

  # GET /manuscripts/1/edit
  def edit
  end

  # POST /manuscripts
  # POST /manuscripts.json
  def create
    @manuscript = Manuscript.new(manuscript_params)

    respond_to do |format|
      if @manuscript.save
        format.html { redirect_to @manuscript, notice: 'Manuscript was successfully created.' }
        format.json { render :show, status: :created, location: @manuscript }
      else
        format.html { render :new }
        format.json { render json: @manuscript.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manuscripts/1
  # PATCH/PUT /manuscripts/1.json
  def update
    respond_to do |format|
      if @manuscript.update(manuscript_params)
        format.html { redirect_to @manuscript, notice: 'Manuscript was successfully updated.' }
        format.json { render :show, status: :ok, location: @manuscript }
      else
        format.html { render :edit }
        format.json { render json: @manuscript.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manuscripts/1
  # DELETE /manuscripts/1.json
  def destroy
    @manuscript.destroy
    respond_to do |format|
      format.html { redirect_to manuscripts_url, notice: 'Manuscript was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manuscript
      @manuscript = Manuscript.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manuscript_params
      params.require(:manuscript).permit(:repository, :call_number, :ms_format)
    end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:paper_height, :paper_width, :chain_lines, :format, :name, :result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manuscripts_helper.rb
module ManuscriptsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaperSizer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/manuscripts/_form.html.erb
<%= form_for(@manuscript) do |f| %>
  <% if @manuscript.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manuscript.errors.count, "error") %> prohibited this manuscript from being saved:</h2>

      <ul>
      <% @manuscript.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :repository %><br>
    <%= f.text_field :repository %>
  </div>
  <div class="field">
    <%= f.label :call_number %><br>
    <%= f.text_field :call_number %>
  </div>
  <div class="field">
    <%= f.label :ms_format %><br>
    <%= f.text_field :ms_format %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manuscripts/edit.html.erb
<h1>Editing Manuscript</h1>

<%= render 'form' %>

<%= link_to 'Show', @manuscript %> |
<%= link_to 'Back', manuscripts_path %>

app/views/manuscripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manuscripts</h1>

<table>
  <thead>
    <tr>
      <th>Repository</th>
      <th>Call number</th>
      <th>Ms format</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manuscripts.each do |manuscript| %>
      <tr>
        <td><%= manuscript.repository %></td>
        <td><%= manuscript.call_number %></td>
        <td><%= manuscript.ms_format %></td>
        <td><%= link_to 'Show', manuscript %></td>
        <td><%= link_to 'Edit', edit_manuscript_path(manuscript) %></td>
        <td><%= link_to 'Destroy', manuscript, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manuscript', new_manuscript_path %>

app/views/manuscripts/new.html.erb
<h1>New Manuscript</h1>

<%= render 'form' %>

<%= link_to 'Back', manuscripts_path %>

app/views/manuscripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Repository:</strong>
  <%= @manuscript.repository %>
</p>

<p>
  <strong>Call number:</strong>
  <%= @manuscript.call_number %>
</p>

<p>
  <strong>Ms format:</strong>
  <%= @manuscript.ms_format %>
</p>

<%= link_to 'Edit', edit_manuscript_path(@manuscript) %> |
<%= link_to 'Back', manuscripts_path %>

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paper_height %><br>
    <%= f.text_field :paper_height %>
  </div>
  <div class="field">
    <%= f.label :paper_width %><br>
    <%= f.text_field :paper_width %>
  </div>
  <div class="field">
    <%= f.label :chain_lines %><br>
    <%= f.text_field :chain_lines %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_area :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Papers</h1>

<table>
  <thead>
    <tr>
      <th>Paper height</th>
      <th>Paper width</th>
      <th>Chain lines</th>
      <th>Format</th>
      <th>Name</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.paper_height %></td>
        <td><%= paper.paper_width %></td>
        <td><%= paper.chain_lines %></td>
        <td><%= paper.format %></td>
        <td><%= paper.name %></td>
        <td><%= paper.result %></td>
        <td><%= link_to 'Show', paper %></td>
        <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
        <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paper height:</strong>
  <%= @paper.paper_height %>
</p>

<p>
  <strong>Paper width:</strong>
  <%= @paper.paper_width %>
</p>

<p>
  <strong>Chain lines:</strong>
  <%= @paper.chain_lines %>
</p>

<p>
  <strong>Format:</strong>
  <%= @paper.format %>
</p>

<p>
  <strong>Name:</strong>
  <%= @paper.name %>
</p>

<p>
  <strong>Result:</strong>
  <%= @paper.result %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>